# Generated by Django 3.0.8 on 2020-07-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
                ('confirmpassword', models.CharField(max_length=25)),
                ('collegename', models.CharField(max_length=50)),
                ('collegeemail', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField(max_length=50)),
                ('address', models.CharField(max_length=60)),
            ],
        ),
    ]
