# Generated by Django 3.0.8 on 2020-07-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version2020', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='phone',
        ),
    ]
