# Generated by Django 3.0.8 on 2020-07-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version2020', '0003_auto_20200728_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
                ('confirmpassword', models.CharField(max_length=25)),
                ('collegename', models.CharField(max_length=50)),
                ('collegeemail', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
